### ISSUE TITLE
[Bug] AGG使用过程中搜索任意数值会改变selinux变成宽容模式状态。正常情况下selinux状态为严格模式

### ISSUE THREAD

**Issue by wangluonvzhu** [AGameGuardian/feedback#7]
### 复现步骤 / Steps to reproduce

1.agg使用过程中搜索任意数值都会导致selinux变为宽容模式selinux正常情况下是严格模式部分游戏会检测这个selinux如不是严格模式将会导致无法进入游戏原版gg也存在这个问题但原版gg有提供一个解决方法在修复功能里面有一个切换到工作而selinux并重新启动应用程序这样完再搜索任意数值都不会导致selinux变成宽容模式状态。

### 预期行为 / Expected behaviour

1.agg使用过程中搜索任意数值都会导致selinux变为宽容模式selinux正常情况下是严格模式部分游戏会检测这个selinux如不是严格模式将会导致无法进入游戏原版gg也存在这个问题但原版gg有提供一个解决方法在修复功能里面有一个切换到工作而selinux并重新启动应用程序这样完再搜索任意数值都不会导致selinux变为宽容模式。

### 实际行为 / Actual behaviour

1.agg使用过程中搜索任意数值都会导致selinux变为宽容模式selinux正常情况下是严格模式部分游戏会检测这个selinux如不是严格模式将会导致无法进入游戏原版gg也存在这个问题但原版gg有提供一个解决方法在修复功能里面有一个切换到工作而selinux并重新启动应用程序这样完再搜索任意数值都不会导致selinux变为宽容模式。

### 你的安卓系统版本 / Your Android version

安卓14

### 应用版本 / App Version

agg3.4.96

### 文件 / File

![Screenshot_2024-10-10-17-55-43-887_io github vvb2060 mahoshojo](https://github.com/user-attachments/assets/9e518a54-2b25-4aff-939b-d7c38ced74fb)

### 补充说明（可选） / Additional information (optional)

希望您能移植一下原版GG里的修复功能里面的切换到工作selinux这样子selinux不会受修改器影响从而改变状态

**Comment by lintianyou** [comment]
![Uploading Screenshot_2024-10-10-18-10-36-082_com.netease.cloudmusic.jpg…]()
